#!/bin/bash

echo "=== Supabase Redirect URL Configuration Instructions ==="
echo ""
echo "To fix the Google sign-in issue, you need to add the redirect URL to your Supabase dashboard:"
echo ""
echo "1. Go to your Supabase dashboard: https://app.supabase.com"
echo "2. Navigate to your project"
echo "3. Go to Authentication > URL Configuration"
echo "4. In the 'Additional Redirect URLs' field, add:"
echo "   asap://oauth/callback"
echo ""
echo "5. Click 'Save'"
echo ""
echo "Current configuration:"
echo "- Deep link scheme: asap"
echo "- Host: oauth"
echo "- Path: /callback"
echo "- Full URL: asap://oauth/callback"
echo ""
echo "This will allow the Google OAuth flow to redirect back to your Android app."
echo ""
echo "After adding the redirect URL, test the Google sign-in again."